version: '3.5'
services:
  app:
    build: .
    volumes:
      - "./src:/var/www/html:ro"
    ports:
      - "80:8080"
  sut:
    image: alpine:3.10
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
